version: '3.0'

networks:
  main:
    driver: bridge

services:
  main:
    container_name: main-povisual
    hostname: main-povisual
    stdin_open: true
    build:
      context: .
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5001:5001 # backend
      # - 5002:5002 # backend
      # - 4200:4200 # frontend
      # - 4400:4400 # storybook
    restart: always
    command: yarn start:dev
    depends_on:
      - postgres
    links: 
      - postgres
    networks:
      - main
  postgres:
    container_name: postgres-povisual
    hostname: postgres
    image: postgres:16
    env_file:
      - .env.local
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 6432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - main

volumes:
  pgdata: